- name: Install kube* Package
  hosts: all
  tasks:
    - name: Adding K8s Repo
      ansible.builtin.template:
        src: ./kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
        owner: root
        group: root
        mode: '0644'
    - name: Update
      dnf:
        name: '*'
        state: latest
    - name: Install Package
      dnf:
        name: "{{item}}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl
    - name: Configure node ip
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted