- hosts: all
  tasks:
    - name: Enable EPEL Repository on CentOS 8
      yum:
        name: epel-release
        state: latest
    - name: Update
      yum:
        name: '*'
        state: latest
    - name: Install Package
      yum:
        name: "{{item}}"
        state: latest
      loop:
        - wget
        - curl
        - vim
        - git
        - net-tools
